apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: localopr
  namespace: tekton-pipelines
spec:
  sourceType: grpc
  image: nikhilvep/operator-registry:0.0.13
  displayName: localOperators
  publisher: LocalDev
